spring:
  datasource:
    url: ${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_DEFAULT_SCHEMA}
        integrator_provider: com.github.ruben_bottu.isp_class_schedule_backend.data_access.ClassImportIntegratorIntegratorProvider
        generate_statistics: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:init-data/setup.sql, classpath:init-data/load.sql, classpath:init-data/insert.sql

logging:
  level:
    org.hibernate.sql: debug

class-schedule:
  default-solution-count: 10
  max-solution-count: 20
  max-course-ids-size: 30
