spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=isp_class_schedule
    username: postgres
    password: t
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: isp_class_schedule
        generate_statistics: true
        integrator_provider: com.github.ruben_bottu.isp_class_schedule_backend.data_access.ClassImportIntegratorIntegratorProvider
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:init-data/setup.sql, classpath:init-data/load.sql, classpath:init-data/insert.sql

logging:
  level:
    org.hibernate.sql: debug

class-schedule:
  default-solution-count: 10
  max-solution-count: 20
  max-course-ids-size: 30

